name: Daily Jekyll Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Optional: allows manual trigger from GitHub UI

permissions:
  contents: write  # Needed to create releases

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Archive _site
        run: |
          tar -czf jekyll-site.tar.gz -C _site .

      - name: Get date
        id: datestamp
        run: echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release with date
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.datestamp.outputs.date }}
          name: "Backup ${{ steps.datestamp.outputs.date }}"
          body: |
            Daily automatic backup for ${{ steps.datestamp.outputs.date }} UTC
            Commit: ${{ github.sha }}
          artifacts: jekyll-site.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
